### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by gallexme** [gamebooster/witcher3-booster#1]
newest version :/
## Red Engine Crash Log

Build: Not Set [ Compiled May 17 2015 ]

Crash reason: EXCEPTION_ACCESS_VIOLATION (3221225477), Error reading location 0x4000003c

Crashed Thread:

Thread ID: 11996

callstack:
DestroyInterface() + 0x61a - <Unknown File>(0)
DestroyInterface() + 0x2d28 - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# Debug Information

Commandline: "X:\The Witcher 3 Wild Hunt\bin\x64\witcher3.exe"  

Thread ID: 11188

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x9f6 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x21a6d - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xc59 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xd4c - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x267d38 - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 1652

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb17477 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 13096

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 1600

callstack:
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 8876

callstack:
DllUnregisterServer() + 0x45ad - <Unknown File>(0)
DllUnregisterServer() + 0x48a6 - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 5292

callstack:
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 10356

callstack:
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 4152

callstack:
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 8208

callstack:
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 4704

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 11148

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 9912

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 11980

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 4112

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 11072

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x811ac - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 10632

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 9488

callstack:
OpenAdapter10() + 0xbdd50 - <Unknown File>(0)
OpenAdapter10() + 0xb605d - <Unknown File>(0)
NVAPI_Thunk() + 0x767aa - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 3940

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 10948

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 5848

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 10280

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 8004

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 1268

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 6112

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 1536

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 12928

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 12916

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 5980

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 10772

callstack:
DllUnregisterServer() + 0x45ad - <Unknown File>(0)
DllUnregisterServer() + 0x48a6 - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 3000

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb29c00 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fc57 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x26fdfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 8728

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Thread ID: 5976

callstack:
OpenAdapter10() + 0x18f11f - <Unknown File>(0)
NVAPI_Thunk() + 0x41baf7 - <Unknown File>(0)
NVAPI_Thunk() + 0x41bc9e - <Unknown File>(0)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)
# 

Game
# 

Game
# 

and custom debug build error:
callstack:
hook::executable_meta::EnsureInit() + 0x59 - x:\the witcher 3 wild hunt\build\hooking\hooking.patterns.cpp(108)
hook::pattern::EnsureMatches() + 0xb5 - x:\the witcher 3 wild hunt\build\hooking\hooking.patterns.cpp(163)
hook::pattern::count() + 0x52 - x:\the witcher 3 wild hunt\build\hooking\hooking.patterns.h(74)
InitializeHook() + 0x6e - x:\the witcher 3 wild hunt\build\main.cc(18)
BaseThreadInitThunk() + 0x22 - <Unknown File>(0)
RtlUserThreadStart() + 0x34 - <Unknown File>(0)

**Comment by skomski** [comment]
sry forgot that base was hardcoded - fixed it in new release https://github.com/gamebooster/witcher3-booster/releases/tag/0.1.1
