### ISSUE TITLE
Sorry to ask

### ISSUE THREAD

**Issue by Goten87** [gamebooster/witcher3-booster#2]
Hello sorry to ask this but i wanted to install your mod when I place the .dll file and the map in the folder you say my witcher game don't even wanne start up am I doing somthing wrong

**Comment by skomski** [comment]
Install https://www.microsoft.com/en-us/download/details.aspx?id=40784 and newest version http://www.nexusmods.com/witcher3/download/170.

Please report back.

**Comment by Goten87** [comment]
din't need to download the microsoft thing just needed new version of you mod now it works ^^
