### ISSUE TITLE
Patch 1.05 breaks the console

### ISSUE THREAD

**Issue by Terr4** [gamebooster/witcher3-booster#4]
The newest patch 1.05 breaks the console plugin, it is no longer possible to open it with F2 or ~. Unfortunately it is also not possible to uninstall this patch from the game.

**Comment by mjhandy** [comment]
So it's not just me then.

M

**Comment by RiccardoGuglielmo** [comment]
We expect an update that works with 1.05!

Thanks for all!

**Comment by phaerus** [comment]
So there's been an update, don't know if it's been posted here / committed to GitHub.

There's a Reddit thread with a replacement DLL file and explanation linked here --http://www.reddit.com/r/witcher/comments/38sqfj/debug_console_enabler_fix_for_105/ and 

Though direct link https://mega.nz/#!zlsW2CLC!Ov8TUIczXlA9ofDdAAuaHiSTpaczb-xbs76EUSjw9yg 

I don't know who can re-compile and update here, though.

**Comment by Nalatroz** [comment]
You can see the changes to make it work at : https://github.com/Nalatroz/witcher3-booster

Mostly just changed a number from 128 to 129 :P
