### ISSUE TITLE
Solve infinite load of "Giant of Undvik" by console

### ISSUE THREAD

**Issue by RiccardoGuglielmo** [gamebooster/witcher3-booster#5]
Hi!

I have a heavy bug with quest of Undvik. I have a infinite loading screen when I combat with giant. If I'm in Novigrad or in other place, if I cast a sign, automatically start the cut scene with giant and the infinite loading.

Can I fix it by console? For example, solve/restart quest of Undvik or defeat giant or Folan NPC.

It's possible to find this bug here: http://forums.cdprojektred.com/threads/39911-The-Lord-of-Undvik-Infinite-Load-Screen

**Comment by skomski** [comment]
http://forums.cdprojektred.com/threads/39911-The-Lord-of-Undvik-Infinite-Load-Screen?p=1823367&viewfull=1#post1823367
