### ISSUE TITLE
error running the game.

### ISSUE THREAD

**Issue by hitmanrd** [gamebooster/witcher3-booster#8]
Using latest version you get the error below, removing dsound.dll fix it but console doesn't work either way. Accepting the error crashes the game.

http://www.reddit.com/r/witcher/comments/3dqyrt/107_game_doesnt_launch_matchescounterror/

**Comment by skomski** [comment]
For patch 1.10: https://github.com/gamebooster/witcher3-booster/releases/tag/0.4
